[project]
name = "curl-wrapper"
dynamic = ["version"]
authors = [
    {name ="Ryan Nowakowski", email="ryan@fattuba.com"},
]
description = "A Python wrapper for curl with a requests-like interface"
readme = "README.md"
requires-python = ">=3.12"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[setuptools-scm]

[tool.setuptools_scm]
